name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes com cobertura
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}  # Adicione esta linha para usar o segredo
      run: npm test
    
    - name: Publicar cobertura no Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
