name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Instalar dependências
      run: npm install

    - name: Configurar variáveis de ambiente
      env:
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}

    - name: Executar testes com cobertura
      run: npm test

    - name: Publicar cobertura no Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
