name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes com cobertura
      env:
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}  # Adicionando a variável de ambiente aqui
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Se precisar do token aqui também
      run: npm test

    - name: Publicar cobertura no Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
